import type { Tool } from '../../../src/lib/types'
import { toolRegistry } from './registry'
import * as fs from 'fs'
import * as path from 'path'

// ============================================================
// Document Generation Tools
// ============================================================

const generateReportTool: Tool = {
  name: 'doc_generate',
  description:
    'Generate a document (report, article, memo, etc.) in Markdown format. Provide title and content.',
  category: 'document',
  parameters: [
    { name: 'title', type: 'string', description: 'Document title', required: true },
    { name: 'content', type: 'string', description: 'Document body content in Markdown format', required: true },
    { name: 'outputPath', type: 'string', description: 'Optional output file path. Defaults to desktop.', required: false },
  ],
  async execute(params) {
    const title = params.title as string
    const content = params.content as string
    const outputPath =
      (params.outputPath as string) ||
      path.join(require('os').homedir(), 'Desktop', `${title.replace(/[<>:"/\\|?*]/g, '_')}.md`)

    const markdown = `# ${title}\n\n> Generated by BspBuddy\n\n${content}`

    const dir = path.dirname(outputPath)
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true })
    }

    fs.writeFileSync(outputPath, markdown, 'utf-8')

    return {
      success: true,
      data: { title, outputPath },
      artifacts: [
        {
          name: path.basename(outputPath),
          path: outputPath,
          mimeType: 'text/markdown',
          size: Buffer.byteLength(markdown),
        },
      ],
    }
  },
}

const generateCsvTool: Tool = {
  name: 'data_csv',
  description:
    'Generate a CSV file from structured data. Provide headers as an array of strings and rows as an array of arrays.',
  category: 'data',
  parameters: [
    { name: 'fileName', type: 'string', description: 'Output CSV file name (without extension)', required: true },
    { name: 'headers', type: 'array', description: 'Column headers', required: true },
    { name: 'rows', type: 'array', description: 'Data rows (array of arrays)', required: true },
    { name: 'outputPath', type: 'string', description: 'Optional output directory', required: false },
  ],
  async execute(params) {
    const fileName = params.fileName as string
    const headers = params.headers as string[]
    const rows = params.rows as unknown[][]
    const outputPath =
      (params.outputPath as string) ||
      path.join(require('os').homedir(), 'Desktop', `${fileName}.csv`)

    const csvContent = [
      headers.join(','),
      ...rows.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(',')),
    ].join('\n')

    const dir = path.dirname(outputPath)
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true })
    }

    fs.writeFileSync(outputPath, csvContent, 'utf-8')

    return {
      success: true,
      data: { fileName, outputPath, rowCount: rows.length, columnCount: headers.length },
      artifacts: [
        {
          name: path.basename(outputPath),
          path: outputPath,
          mimeType: 'text/csv',
          size: Buffer.byteLength(csvContent),
        },
      ],
    }
  },
}

// Register all document tools
export function registerDocumentTools(): void {
  toolRegistry.register(generateReportTool)
  toolRegistry.register(generateCsvTool)
}
